package eventplannerUT;

import static java.nio.file.StandardOpenOption.APPEND;
import static java.nio.file.StandardOpenOption.CREATE;

import java.io.BufferedOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;

/**
 * Logging class used as a utility for the event planner.
 * Each developer needs to edit the path if they want to make use of this class.
 * @author David.North
 *
 */
public class Log {
    
	/**
	 * Default No Argument constructor
	 */
	public Log() {};
	
	/**
	 * Method that logs the message out to a file in the file system
	 * @param message - the text to be written in the log file
	 */
	public void log(String message) {
		String message1 = message + "\n";
		byte data[] = message1.getBytes();
		Path p = Paths.get("/Users/rdnot/Desktop/eventplannerlog.txt");
		
		try (OutputStream out = new BufferedOutputStream(
				Files.newOutputStream(p, CREATE, APPEND))) {
			out.write(data,  0,  data.length);
			out.close();
		} catch (IOException x) {
			
		}
	}
	
	/**
	 * Attempts to collect the schema that is generated by the jaxb annotation
	 * unmarshalling process.
	 * Search for Schema1.xsd to find the generated schema.
	 */
	public void logJAXB() {
		@SuppressWarnings("rawtypes")
		Class[] classes = new Class[10];
		classes[0] = eventplannerPD.Company.class;
		classes[1] = eventplannerPD.Customer.class;
		classes[2] = eventplannerPD.Event.class;
		classes[3] = eventplannerPD.Guest.class;
		classes[4] = eventplannerPD.GuestGuestAvoidBridge.class;
		classes[5] = eventplannerPD.GuestGuestSitWithBridge.class;
		classes[6] = eventplannerPD.GuestList.class;
		classes[7] = eventplannerPD.SeatingArrangement.class;
		classes[8] = eventplannerPD.Table.class;
		classes[9] = eventplannerPD.User.class;
		try {
			JAXBContext jaxbContext = JAXBContext.newInstance(classes);
			jaxbContext.generateSchema(new SchemaOutputResolver());
		} catch (JAXBException | IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
